---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 35169.
--- DateTime: 2026/7/23 17:53
---

local curr_count = redis.call('INCR',KEYS[1])
if curr_count == 1 then
    redis.call('EXPIRE', KEYS[1], ARGV[1])
end
return curr_count;

